name: CD Pipeline

on:
  workflow_run:
    workflows: ["simple React CI workflow pipeline"] # CI workflow name (must match exactly)
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' # ✅ Ensure CI finished successfully
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Print triggering workflow event
        run: echo '${{ toJSON(github.event.workflow_run) }}'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build # Must match artifact name in CI
          run-id: ${{ github.event.workflow_run.id }}

      - name: Show downloaded files
        run: ls -R

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name react-test
