name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["simple React CI workflow pipeline"]
    types:
      - completed
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu
    environment: production

    steps:
      - name: "Setup Nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Setup Vercel CLI"
        run: npm i -g vercel@latest

      - name: "Debug: Print event payload"
        run: echo '${{ toJSON(github.event) }}'

      - name: "Download build files"
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: "Deploy to Vercel"
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name react-test
