name: CD Pipeline

on:
  workflow_run:
    workflows: ["simple React CI workflow pipeline"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Print workflow run ID
        run: echo "Workflow Run ID ${{ github.event.workflow_run.id }}"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id }}

      - name: Debug downloaded files
        run: ls -R

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name react-test
