name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["simple React CI workflow pipeline"] # 👈 Make sure this matches the CI name
    types:
      - completed

  workflow_dispatch:

permissions:
  actions: read # ✅ Required for download-artifact
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Log Triggering Event
        run: echo '${{ toJSON(github.event) }}'

      - name: Debug Workflow Run Info
        run: echo 'Workflow Run ID ${{ github.event.workflow_run.id }}'

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id }}

      - name: Show Build Files
        run: ls -la

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name react-test
